name: Django CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10,3.11,3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run MakeMigrations
      run: |
        python manage.py makemigrations
    - name: Run MakeMigrations cartera
      run: |
       python manage.py makemigrations cartera
    - name: Run Migrate
      run: |
        python manage.py migrate
    - name: Run Test cartera
      run: |
        python manage.py test cartera
